### ISSUE TITLE
Implementation for Django restframwork

### ISSUE THREAD

**Issue by assem-ch** [antiproblemist/django-accountkit#1]
Have you an idea how to wrap this to use it with DRF to implement an API consumable by a mobile app?

**Comment by antiproblemist** [comment]
Your template will contain the Javascript and form which will be submitted after the user is authenticated from account kit and the success URL as mentioned in the documentation will be you api where you are going to receive the parameters sent by account kit

**Comment by nitrag** [comment]
I'm not following. Can someone post an example.

**Comment by antiproblemist** [comment]
Please follow the README document for setting it up with your django project

**Comment by assem-ch** [comment]
@antiproblemist how I can know what user is authenticated ?

**Comment by antiproblemist** [comment]
@assem-ch After the `login_status` function is called it returns the user object in the dictionary
The user object is only returned if the user has been successfully authenticated
