### ISSUE TITLE
Can't install via pip

### ISSUE THREAD

**Issue by nitrag** [antiproblemist/django-accountkit#3]
I'm using Python 3.6, is it not compatible via pip?

```
pip install django-accountkit
Collecting django-accountkit
  Could not find a version that satisfies the requirement django-accountkit (from versions: )
No matching distribution found for django-accountkit
```

**Comment by antiproblemist** [comment]
The package is right now only compatible with python 2.7. The code needs to be made compatible with python 3. Definitely the next release is going to be compatible with python 3. I also need some contributors for maintaining this package
