### ISSUE TITLE
Django 2 support

### ISSUE THREAD

**Issue by hasnat-abdullah** [antiproblemist/django-accountkit#4]
Now Django 2 is very popular. But this amazing Django-Accountkit app is not working in django 2. 
When i try to install with pip, then it fails with this message:  
"Could not find a version that satisfies the requirement django-accountkit (from versions: )
No matching distribution found for django-accountkit"

Wish you update for Django 2.1 as soon as possible. Thank you

**Comment by antiproblemist** [comment]
Hi, the package has been updated to support python 3.7 and django 2.1
