### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by subhamhota** [antiproblemist/django-accountkit#5]
I am not that much experienced in Django.
can u explain a bit more in the documentation?
Unable to make things happen.

**Comment by antiproblemist** [comment]
Please describe the issue you are facing

**Comment by subhamhota** [comment]
after pip install how to map "django-accountkit" into my project and as it has no URL structure pre-written how to do that in my project etc.
and
Is HTTPS is a must have to use this project?

**Comment by antiproblemist** [comment]
django-accountkit does not need any pre writtern url-structure. You can create your own login, signup, logout urls and implement the [view ](https://github.com/antiproblemist/django-accountkit#view) inside your views and [template tags](https://github.com/antiproblemist/django-accountkit#template-tags) inside your templates.
Please read the installation documentation here [Installation](https://github.com/antiproblemist/django-accountkit#installation).

HTTPS is always recommended for authentication in the production environment, however there should not be any issue working with http unless facebook restricts it

**Comment by subhamhota** [comment]
the page is coming blank.

i am using Django 2.2

`INSTALLED_APPS = [
    'accountkitlogin',
    +with my other apps
]
APP_ID = '##############'
ACCOUNT_KIT_APP_SECRET = '####################'
ACCOUNT_KIT_VERSION = "v1.0"
ACCOUNT_KIT_SUCCESS_REDIRECT = 'http://127.0.0.1:8000/success'

FACEBOOK_APP_ID = '#################'
`

views.py
`from django.views.decorators.csrf import csrf_exempt
from accountkitlogin.views import login_status
@csrf_exempt
def success_page(request):
    context = login_status(request)

def start_page(request):
    return render(request,'accountkitlogin/accountkit.html')`

urls.py

`from django.urls import path
from . import views

urlpatterns = [
    path('success/',views.success_page),
    path('loginpage/',views.start_page),
]
`
accountkitlogin/accountkit.html
`{% extends "blog/base.html" %}
{% load accountkit %}


{% block content %}

{% accountkitjs %}
{% accountkitform %}
{% smslogin "button" "Login via SMS" %}
{% endblock content %}`

**Comment by subhamhota** [comment]
the page is coming blank.

i am using Django 2.2

settings.py

> INSTALLED_APPS = [
'accountkitlogin',
+with my other apps
]
APP_ID = '##############'
ACCOUNT_KIT_APP_SECRET = '####################'
ACCOUNT_KIT_VERSION = "v1.0"
ACCOUNT_KIT_SUCCESS_REDIRECT = 'http://127.0.0.1:8000/success'
FACEBOOK_APP_ID = '#################'



views.py

> from django.views.decorators.csrf import csrf_exempt
from accountkitlogin.views import login_status
@csrf_exempt
def success_page(request):
context = login_status(request)
def start_page(request):
return render(request,'accountkitlogin/accountkit.html')

urls.py

> from django.urls import path
from . import views
urlpatterns = [
path('success/',views.success_page),
path('loginpage/',views.start_page),
]

accountkitlogin/accountkit.html

> {% extends "blog/base.html" %}
{% load accountkit %}
{% block content %}
{% accountkitjs %}
{% accountkitform %}
{% smslogin "button" "Login via SMS" %}
{% endblock content %}

**Comment by antiproblemist** [comment]
It looks like your accountkit.html template  does not have much html code in it
Add `(% accountkitjs %}` inside your `<head></head>` tag
Add `{% accountkitform %}` inside your `<body></body>` tag
Add `{% smslogin %}` and/or `{% emaillogin %}` anywhere in you body section where you want to display your login buttons. Both these tags accept two parameters `className ` and `text `where you can add your custom css classes and the text to display on the button. Example `{% emaillogin "button" "Use the email" %}`

If you are still facing some issues then please post your code with the issue you are facing on the community chat link [Django accountkit on Spectrum Chat](https://spectrum.chat/django-accountkit/general?tab=posts)
